MOUSEKEY_ENABLE     = no     # Mouse keys
RGBLIGHT_ENABLE     = yes    # Enable WS2812 RGB underlight.
SPLIT_KEYBOARD = yes
VIA_ENABLE          = no
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
LTO_ENABLE          = yes
EXTRAFLAGS += -flto
WPM_ENABLE = no